version: "3"

services:
  basicstation:
    build: ./basicstation
    container_name: basicstation
    restart: unless-stopped
    privileged: true

    volumes:
      - ./config:/basicstation/config:ro
