version: "3"

services:
  basicstation:
    build: ./basicstation
    container_name: basicstation
    restart: unless-stopped

    volumes:
      - ./config:/basicstation/config:ro

    devices:
      - /dev/ttyACM0:/dev/ttyACM0
